grafana:
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true

    analytics:
      reporting_enabled: false
      check_for_updates: false
      check_for_plugin_updates: false

    plugins:
      preinstall_disabled: true
      preinstall_auto_update: false
      plugin_admin_enabled: false

  service:
    type: ClusterIP

  persistence:
    enabled: false

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  livenessProbe:
    httpGet:
      path: /api/health
      port: grafana
    initialDelaySeconds: 180
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 10

  readinessProbe:
    httpGet:
      path: /api/health
      port: grafana
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 10


prometheus:
  prometheusSpec:
    retention: 7d

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi


alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi