[all]
k8s-control-plane ansible_host=10.10.1.4 ip=10.10.1.4 access_ip=10.10.1.4 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyJump=ubuntu@111.88.156.201'
k8s-worker-1 ansible_host=111.88.156.201 ip=10.10.2.22 access_ip=10.10.2.22 ansible_user=ubuntu
k8s-worker-2 ansible_host=10.10.3.30 ip=10.10.3.30 access_ip=10.10.3.30 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyJump=ubuntu@111.88.156.201'

[kube_control_plane]
k8s-control-plane

[etcd]
k8s-control-plane

[kube_node]
k8s-worker-1
k8s-worker-2

[k8s_cluster:children]
kube_control_plane
kube_node